"use client";
import {ChevronDown,Edit3,Search,Upload,Sparkles} from './ui-icons';
import {WorkflowButton,WorkflowFeedback} from './workflow-feedback';
import {constraintLabel} from '@/visual-rules/constraint-scope.mjs';
import type {BriefAnalysis} from '@/lib/brief';

export default function DirectionReview({analysis,supplement,onSupplement,loading,confirmed,onRevise,onRetrieve,onUpload,mode,catalogReady,uploadReady,noneReady,onNone}:{analysis:BriefAnalysis;supplement:string;onSupplement:(value:string)=>void;loading:string;confirmed:boolean;onRevise:()=>void;onRetrieve:()=>void;onUpload:()=>void;mode:'catalog'|'upload'|'none';catalogReady:boolean;uploadReady:boolean;noneReady:boolean;onNone:()=>void}) {
  const blocked=analysis.unsupportedConstraints.length>0;
  const hasSupplement=Boolean(supplement.trim());
  return <section className="direction-review" aria-label="设计方向确认">
    <header className="direction-heading"><div><span className="eyebrow">需求分析结果 · 第 {analysis.revision} 版</span><h3>确认设计方向</h3></div><span className={`badge badge-${confirmed?'success':'neutral'}`}>{confirmed?'方向已确认':'等待确认'}</span></header>
    <div className={`direction-grid ${mode!=='catalog'?'direction-grid-upload':''}`}>
      <div className="direction-summary"><h4>设计方向</h4><p>{analysis.designDirection}</p><h4>风格关键词</h4><ul className="direction-keywords">{analysis.designKeywords.map((keyword,index)=><li key={keyword}><span>{String(index+1).padStart(2,'0')}</span>{keyword}</li>)}</ul></div>
      {mode==='catalog'&&<aside className="direction-filters"><h4>素材检索范围</h4><dl><div><dt>物料</dt><dd>{analysis.materialType}</dd></div><div><dt>年级</dt><dd>{analysis.grade==='未指定'?'不限年级':analysis.grade}</dd></div><div><dt>学科</dt><dd>{analysis.subject==='未指定'?'不限学科':analysis.subject}</dd></div></dl><p>未指定项不限制检索。设计关键词用于匹配相似视觉。</p></aside>}
    </div>
    <details className="direction-details constraint-details"><summary><ChevronDown size={15}/>成图要求与参考筛选</summary><div><h4>最终图片要做到</h4>{analysis.generationConstraints?.length?analysis.generationConstraints.map((rule,index)=><p key={index}><b>{constraintLabel(rule)}</b><small>来源：{rule.evidence}</small></p>):<p>按你填写的文案、画面与主体要求生成。</p>}{analysis.generationNotes?.map(note=><p key={note}>{note}</p>)}<h4>参考素材筛选</h4>{analysis.hardConstraints.length?analysis.hardConstraints.map((rule,index)=><p key={index}><b>{constraintLabel(rule)}</b><small>来源：{rule.evidence}</small></p>):<p>未额外限定参考图片。标题、卖点数量和动作等成图要求不会逐张检查参考。</p>}</div></details>
    <details className="direction-details"><summary><ChevronDown size={15}/>查看分析依据与待确认假设</summary><div><p>目标用户：{analysis.audience} · 使用场景：{analysis.usageScenario}</p><p>产品价值：{analysis.productValue} · 情绪价值：{analysis.emotionalValue}</p>{analysis.assumptions.map(item=><p key={item}>{item}</p>)}{mode==='catalog'&&<p>检索描述：{analysis.searchQuery}</p>}</div></details>
    {blocked&&mode!=='none'&&<div className="direction-blocker" role="alert"><b>以下参考图限制暂时无法自动验证</b><ul>{analysis.unsupportedConstraints.map(item=><li key={item}>{item}</li>)}</ul><p>请在下方补充可验证的要求，或明确将这些限制改为偏好，再修正方向。系统不会自动放宽限制。</p></div>}
    <div className="direction-supplement"><label htmlFor="direction-supplement">补充或调整方向 <span>选填</span></label><textarea id="direction-supplement" disabled={Boolean(loading)} value={supplement} onChange={event=>onSupplement(event.target.value)} placeholder="例如：改为插画，不要真人"/><div className="direction-supplement-footer"><span>{hasSupplement?'有新的补充，请先修正方向。':blocked?'请补充如何处理上方限制，再修正方向。':'确认方向后，从下方选择一种参考方式。'}</span><WorkflowButton className="button button-secondary" onClick={onRevise} disabled={Boolean(loading)||!hasSupplement} busy={loading==='reviseBrief'} loadingText="正在修正方向…" icon={<Edit3 size={15}/>}>修正设计方向</WorkflowButton></div></div>
    <WorkflowFeedback busy={loading==='reviseBrief'} title="Luna 正在修正设计方向" detail="结合最新补充，保留原有无冲突要求。"/>
    <div className="reference-branch-choices" role="group" aria-label="参考方式"><section className={`branch-catalog ${mode==='catalog'?'branch-active':''}`}><h4><Search size={18}/>套系库检索{mode==='catalog'&&<small>当前模式</small>}</h4><p>复用已有项目；也可补充上传 IP。</p><WorkflowButton aria-pressed={mode==='catalog'} className="button button-secondary" onClick={onRetrieve} disabled={Boolean(loading)||hasSupplement||blocked} busy={loading==='retrieve'} loadingText="正在检索素材…" icon={<Search size={16}/>}>{catalogReady?'继续套系库参考':'确认方向并检索'}</WorkflowButton></section><section className={`branch-upload ${mode==='upload'?'branch-active':''}`}><h4><Upload size={18}/>独立上传参考{mode==='upload'&&<small>当前模式</small>}</h4><p>不检索项目；直接上传风格、排版或 IP。</p><WorkflowButton aria-pressed={mode==='upload'} className="button button-secondary" onClick={onUpload} disabled={Boolean(loading)||hasSupplement||blocked} busy={loading==='start-upload'} loadingText="正在准备上传…" icon={<Upload size={16}/>}>{uploadReady?'继续独立上传参考':'确认方向并上传参考'}</WorkflowButton></section><section className={`branch-none ${mode==='none'?'branch-active':''}`}><h4><Sparkles size={18}/>无参考创作{mode==='none'&&<small>当前模式</small>}</h4><p>不检索、不上传；直接按需求设计，仍可指定卖点分类。</p><WorkflowButton aria-pressed={mode==='none'} className="button button-secondary" onClick={onNone} disabled={Boolean(loading)||hasSupplement} busy={loading==='start-none'} loadingText="正在准备创作…" icon={<Sparkles size={16}/>}>{noneReady?'继续无参考创作':'确认方向并直接创作'}</WorkflowButton></section></div>
    <p className="branch-switch-note">切换只显示当前模式；本次页面会话内保留各模式的参考、说明和生成设置。修改需求后需重新确认。</p>
    <WorkflowFeedback busy={loading==='retrieve'} title="正在检索已确认素材" detail="按需求筛选并匹配向量，再展开同套系的主参考和辅助图。" variant="comet"/>
  </section>;
}
