"use client";
import {useEffect,useRef,useState} from 'react';
import type {ArchiveAsset} from '@/lib/archive-types';
import type {ReviewInput} from '@/lib/archive';
import type {VisualProfile} from '@/visual-rules/v1/index.mjs';
import {Check,RefreshCw,X,ClipboardCheck} from './ui-icons';
import {WorkflowButton,WorkflowFeedback} from './workflow-feedback';
import VisualFields from './visual-fields';
import VisualProfileView from './visual-profile';
import {canConfirmReview,reviewBlocker} from '@/visual-rules/review-state.mjs';
const materials={GIFT_BOX:'礼盒',BOOK_COVER:'主书封面',TITLE_PAGE:'扉页',PRODUCT_BOOKLET:'产品说明书',WALL_CHART:'挂图',OTHER:'其他'};
type Revision={id:string;asset_id:string;status:string;candidate:VisualProfile|null;confirmed:VisualProfile|null;active_profile:VisualProfile|null;error_message:string|null};
const labels:Record<string,string>={QUEUED:'等待识别',ANALYZING:'正在识别视觉',PENDING:'待确认',APPROVED:'排队入库',PROCESSING_TEXT:'正在生成文本向量',PROCESSING_IMAGE:'正在生成图片向量',READY:'已入库',FAILED:'处理失败，可重试',WAITING_ELIGIBILITY:'等待审核或套系主参考'};
const working=['QUEUED','ANALYZING','APPROVED','PROCESSING_TEXT','PROCESSING_IMAGE'];
function defaults(asset:ArchiveAsset):ReviewInput{return {displayName:asset.displayName,projectName:asset.projectName||'',suiteName:asset.suiteName||'',materialType:asset.materialType,grade:asset.grade,subject:asset.subject,colors:asset.colors,tags:asset.tags,visualStyle:asset.visualStyle,layoutFeatures:asset.layoutFeatures,coreElements:asset.coreElements,ocrText:asset.ocrText,description:asset.description,isPrimary:asset.isPrimary};}
async function api<T>(url:string,body?:unknown,method='PATCH'):Promise<T>{const response=await fetch(url,{method:body?method:'GET',cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
export default function UnifiedReview({assets,onRefresh}:{assets:ArchiveAsset[];onRefresh:()=>Promise<void>}){
 const [revisions,setRevisions]=useState<Revision[]>([]),[filter,setFilter]=useState(''),[selected,setSelected]=useState<string[]>([]),[current,setCurrent]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [edits,setEdits]=useState<Record<string,{fields:ReviewInput;profile:VisualProfile|null;revisionId?:string}>>({});
 const dialog=useRef<HTMLDialogElement>(null);
 async function load(){try{setRevisions(await api<Revision[]>('/api/visual-revisions'));}catch(error){setError(error instanceof Error?error.message:'读取失败');}}
 useEffect(()=>{load();const id=setInterval(load,4000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(current)dialog.current?.showModal();else dialog.current?.close();},[current]);
 const revisionFor=(id:string)=>revisions.find(row=>row.asset_id===id);
 const needsReview=(asset:ArchiveAsset)=>asset.reviewState!=='CONFIRMED'||revisionFor(asset.id)?.status==='PENDING';
 const canConfirm=(asset:ArchiveAsset)=>canConfirmReview(asset,revisionFor(asset.id));
 const pending=assets.filter(canConfirm),processing=assets.filter(asset=>!canConfirm(asset)&&(working.includes(revisionFor(asset.id)?.status||'')||(!revisionFor(asset.id)&&asset.analysisStatus!=='FAILED')));
 const unfinished=assets.filter(asset=>asset.reviewState!=='CONFIRMED'||revisionFor(asset.id)?.status!=='READY');
 const blocked=unfinished.filter(a=>!pending.includes(a)&&!processing.includes(a));
 const suites=[...new Set(assets.map(asset=>asset.suiteId||''))];
 const visible=unfinished.filter(asset=>!filter||asset.suiteId===filter),selectable=visible.filter(canConfirm);
 const asset=assets.find(asset=>asset.id===current),revision=asset?revisionFor(asset.id):undefined;
 const draft=asset?(edits[asset.id]??{fields:defaults(asset),profile:revision?.confirmed??revision?.candidate??null,revisionId:revision?.id}):null;
 function edit(fields:ReviewInput,profile:VisualProfile|null){if(asset&&draft)setEdits(value=>({...value,[asset.id]:{fields,profile,revisionId:draft.revisionId}}));}
 async function action(name:string,run:()=>Promise<{message?:string}>){if(busy)return;setBusy(name);setError('');setMessage('');try{const result=await run();setMessage(result.message||'已提交处理');await Promise.all([load(),onRefresh()]);return true;}catch(error){setError(error instanceof Error?error.message:'操作失败');return false;}finally{setBusy('');}}
 async function confirm(ids:string[]){const ok=await action('confirm',()=>api('/api/review',{items:ids.map(id=>{const a=assets.find(asset=>asset.id===id)!;const r=revisionFor(id);const d=edits[id];return {assetId:id,fields:a.reviewState!=='CONFIRMED'||(d&&JSON.stringify(d.fields)!==JSON.stringify(defaults(a)))?{...(d?.fields??defaults(a)),isPrimary:a.isPrimary}:undefined,revisionId:d?.revisionId??r?.id,profile:d?.profile??r?.candidate};})}));if(ok){setSelected([]);setCurrent('');setEdits({});}}
 const state=(a:ArchiveAsset)=>reviewBlocker(a,revisionFor(a.id),assets.find(p=>p.suiteId===a.suiteId&&p.isPrimary))||(needsReview(a)&&canConfirm(a)?'待确认基础信息与视觉':labels[revisionFor(a.id)?.status||'']||(a.previewUrl?'等待视觉识别':'正在准备预览'));
 return <section className="unified-review work-card"><header className="card-heading"><div><p className="eyebrow">素材入库</p><h2>统一审核</h2><p>一张图确认一次：核对基础信息与视觉规则，确认后自动入库。</p></div><WorkflowButton className="button button-secondary" busy={busy==='retry'} disabled={Boolean(busy)} onClick={()=>action('retry',async()=>{const result=await api<{queued:number}>('/api/visual-revisions',{},'POST');return {message:`已提交 ${result.queued} 张待识别或失败素材`};})}><RefreshCw size={14}/>识别 / 重试</WorkflowButton></header>
 <div className="unified-review-stats"><span><b>{pending.length}</b> 待确认</span><span><b>{processing.length}</b> 处理中</span><span className={blocked.length?'review-attention':''}><b>{blocked.length}</b> 需处理</span><span><b>{assets.filter(a=>a.reviewState==='CONFIRMED'&&revisionFor(a.id)?.status==='READY').length}</b> 已入库</span></div>
 <div className="visual-toolbar"><label>套系<select value={filter} onChange={event=>{setFilter(event.target.value);setSelected([]);}}><option value="">全部套系</option>{suites.map(id=><option key={id} value={id}>{assets.find(a=>a.suiteId===id)?.suiteName||'未归类'}</option>)}</select></label><label><input type="checkbox" disabled={Boolean(busy)||!selectable.length} checked={Boolean(selectable.length)&&selectable.every(a=>selected.includes(a.id))} onChange={event=>setSelected(event.target.checked?selectable.map(a=>a.id):[])}/>全选可确认素材</label><WorkflowButton className="button button-primary" disabled={Boolean(busy)||!selected.some(id=>selectable.some(a=>a.id===id))} busy={busy==='confirm'} loadingText="正在保存审核…" onClick={()=>confirm(selected.filter(id=>selectable.some(a=>a.id===id)))}><Check size={14}/>确认所选</WorkflowButton></div>
 {suites.filter(id=>!filter||id===filter).map(id=>{const group=assets.filter(a=>(a.suiteId||'')===id);const primary=group.find(a=>a.isPrimary);const rows=visible.filter(a=>(a.suiteId||'')===id);if(!rows.length&&primary)return null;return <section className="unified-suite" key={id}>
 <header><div><h3>{group[0].suiteName||'未归类'}</h3><small>{rows.length} 张待处理 · {primary?'已选择主参考':'尚未选择主参考，审核可以先完成'}</small></div></header>
 <details className="suite-primary-choice" open={primary?undefined:true}><summary>{primary?.previewUrl&&<img src={primary.previewUrl} alt=""/>}<span><b>{primary?'当前主参考 · '+primary.displayName:'选择套系主参考'}</b><small>{primary?'点击展开图片，按需更换':'选择最能代表套系整体风格的图片，不会自动确认其审核内容'}</small></span></summary>
 <div className="suite-primary-picker" aria-label={`${group[0].suiteName}主参考图选择`}>{group.filter(a=>a.previewUrl&&a.reuseState!=='NOT_REUSABLE').map(a=><button type="button" key={a.id} aria-pressed={primary?.id===a.id} aria-label={`设为主参考：${a.displayName}`} className={`primary-tile ${primary?.id===a.id?'primary-tile-selected':''}`} disabled={Boolean(busy)||!id} onClick={()=>primary?.id===a.id?undefined:action('primary',()=>api('/api/review',{action:'primary',suiteId:id,assetId:a.id}))}><img src={a.previewUrl||undefined} alt=""/><span>{a.displayName}</span>{primary?.id===a.id&&<b><Check size={12}/>当前主参考</b>}</button>)}</div></details>
 <div className="suite-review-hint">核对素材 → 确认入库 → 后台自动处理，成功后移出队列</div>
 {rows.map(a=><article className="unified-review-row" key={a.id}><input type="checkbox" aria-label={`选择 ${a.displayName}`} disabled={Boolean(busy)||!canConfirm(a)} checked={selected.includes(a.id)} onChange={event=>setSelected(values=>event.target.checked?[...values,a.id]:values.filter(id=>id!==a.id))}/><button className="visual-row-open" onClick={()=>setCurrent(a.id)}>{a.previewUrl?<img src={a.previewUrl} alt={a.displayName}/>:<ClipboardCheck size={24}/>}<span><b>{a.displayName}</b><small>{materials[a.materialType as keyof typeof materials]} · {state(a)}</small>{working.includes(revisionFor(a.id)?.status||'')&&<progress aria-label={state(a)}/>}</span></button>{canConfirm(a)&&<button className="button button-secondary" disabled={Boolean(busy)} onClick={()=>setCurrent(a.id)}>核对并确认</button>}{!canConfirm(a)&&['FAILED','WAITING_ELIGIBILITY'].includes(revisionFor(a.id)?.status||'')&&<button className="button button-secondary" disabled={Boolean(busy)} onClick={()=>revisionFor(a.id)?.status==='WAITING_ELIGIBILITY'&&state(a)!=='资格已补齐，可继续入库'?setCurrent(a.id):action('retry',async()=>{await api('/api/visual-revisions',{assetIds:[a.id]},'POST');return {message:'已重新提交这张素材，后台处理中'};})}><RefreshCw size={14}/>{revisionFor(a.id)?.status==='FAILED'?'重试这张':state(a)==='资格已补齐，可继续入库'?'继续入库':'查看原因'}</button>}</article>)}</section>;})}
 {!unfinished.length&&suites.every(id=>assets.some(a=>a.suiteId===id&&a.isPrimary))&&<p className="visual-queue-empty">当前入库已完成，素材可在项目库查看。</p>}
 <WorkflowFeedback busy={Boolean(busy)} title="正在保存审核" error={error} success={message}/>
 <dialog ref={dialog} className="unified-review-dialog" aria-label="素材统一审核" onClose={()=>setCurrent('')} onCancel={event=>{if(busy)event.preventDefault();}}>{asset&&draft&&<><header><div><h3>{asset.displayName}</h3><small>{state(asset)}</small></div><button className="icon-button" title="关闭" disabled={Boolean(busy)} onClick={()=>setCurrent('')}><X size={18}/></button></header><div className="unified-review-body"><aside>{asset.previewUrl&&<img src={asset.previewUrl} alt={asset.displayName}/>}<p>{asset.filename}</p>{revision?.active_profile&&revision.status!=='READY'&&<details><summary>对照上次发布内容</summary><VisualProfileView profile={revision.active_profile}/></details>}</aside><div><fieldset className="unified-basics" disabled={Boolean(busy)||!canConfirm(asset)}><legend>基础信息{asset.reviewState==='CONFIRMED'?' · 已确认，仅按需修改':''}</legend>{(['displayName','projectName','suiteName','grade','subject'] as const).map((key,index)=><label key={key}>{['素材名称','项目','套系','年级','学科'][index]}<input name={key} value={draft.fields[key]||''} onChange={event=>edit({...draft.fields,[key]:event.target.value},draft.profile)}/></label>)}<label>物料类型<select name="materialType" value={draft.fields.materialType} onChange={event=>edit({...draft.fields,materialType:event.target.value},draft.profile)}>{Object.entries(materials).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></fieldset>
 {draft.profile?<VisualFields profile={draft.profile} disabled={Boolean(busy)||revision?.status!=='PENDING'} onChange={profile=>edit(draft.fields,profile)}/>:<p>正在准备视觉候选；完成后可一次确认所有信息。</p>}
 <details className="unified-ocr"><summary>查看原图文字（OCR）</summary><p>{asset.ocrText||'未识别到文字'}</p></details>{(revision?.error_message||asset.errorMessage)&&<p role="alert">{revision?.error_message||asset.errorMessage}</p>}</div></div><footer><WorkflowFeedback title="保存审核" error={error}/><WorkflowButton className="button button-primary" disabled={Boolean(busy)||!canConfirm(asset)} busy={busy==='confirm'} loadingText="正在保存审核…" onClick={()=>confirm([asset.id])}><Check size={16}/>确认并入库</WorkflowButton></footer></>}</dialog>
 </section>;
}
