"use client";
import {useEffect,useRef,useState} from 'react';
import VisualProfileView from './visual-profile';
import {Check,RefreshCw,X} from './ui-icons';
import {GROUPS,FIELD_LABELS,TITLE_TYPES,SELLING_TYPES,SUBJECT_TYPES,type VisualProfile} from '@/visual-rules/v1/index.mjs';
type Revision={id:string;asset_id:string;filename:string;display_name:string;suite_name:string;status:string;candidate:VisualProfile|null;confirmed:VisualProfile|null;active_profile:VisualProfile|null;legacy_style:string;legacy_layout:string;adaptation_notes:string;reuse_state:string;error_message:string|null;active_visual_revision_id:string|null};
const statuses:Record<string,string>={QUEUED:'等待处理',ANALYZING:'Luna 正在识别',PENDING:'新视觉字段待审核',APPROVED:'已确认，排队向量化',PROCESSING_TEXT:'正在生成文本向量',PROCESSING_IMAGE:'正在生成图片向量',READY:'v1 已发布，可检索',FAILED:'失败，可重试',WAITING_ELIGIBILITY:'等待素材与主参考确认'};
async function api<T>(method='GET',body?:unknown):Promise<T>{const response=await fetch('/api/visual-revisions',{method,cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json().catch(()=>null);if(!response.ok||!data)throw new Error(data?.error||'视觉审核服务暂时不可用');return data;}
export default function VisualReview(){
 const [rows,setRows]=useState<Revision[]>([]),[suite,setSuite]=useState(''),[selected,setSelected]=useState<string[]>([]),[current,setCurrent]=useState<string|null>(null),[edits,setEdits]=useState<Record<string,{profile:VisualProfile;notes:string}>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 async function load(){try{setRows(await api<Revision[]>());}catch(error){setMessage(error instanceof Error?error.message:'读取失败');}}
 useEffect(()=>{load();const timer=setInterval(load,4000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(current)dialog.current?.showModal();else dialog.current?.close();},[current]);
 const visible=rows.filter(row=>row.status!=='READY'&&(!suite||row.suite_name===suite)),row=rows.find(item=>item.id===current);
 const edit=row?(edits[row.id]??{profile:row.candidate??row.confirmed!,notes:row.adaptation_notes}):null;
 function change(profile:VisualProfile,notes:string){if(row)setEdits(value=>({...value,[row.id]:{profile,notes}}));}
 async function upgrade(ids?:string[],force=false){setBusy(true);try{const result=await api<{queued:number}>('POST',ids?{assetIds:ids,force}:{});if(force)setCurrent(null);setMessage(`已提交 ${result.queued} 张，当前已发布索引保持可用。`);await load();}catch(error){setMessage(error instanceof Error?error.message:'升级失败');}finally{setBusy(false);}}
 async function confirm(ids:string[]){setBusy(true);try{await api('PATCH',{items:ids.map(id=>{const item=rows.find(row=>row.id===id)!;const data=edits[id]??{profile:item.candidate,notes:item.adaptation_notes};return {id,profile:data.profile};})});setSelected([]);setCurrent(null);setMessage('视觉字段已确认，等待后台发布。');await load();}catch(error){setMessage(error instanceof Error?error.message:'确认失败');}finally{setBusy(false);}}
 const selectable=visible.filter(item=>item.status==='PENDING'&&item.reuse_state!=='NOT_REUSABLE');
 return <section className="visual-review-section"><header className="card-heading"><div><h2>视觉规则审核</h2><small>v1 · {rows.filter(row=>row.status==='READY').length} 已发布 · {rows.filter(row=>row.status==='PENDING').length} 待确认</small></div><button className="button button-secondary" disabled={busy} onClick={()=>upgrade()}><RefreshCw size={16}/>识别／重试未完成素材</button></header>
 {message&&<div role="status" className="notice">{message}</div>}
 <div className="visual-toolbar"><label>套系<select value={suite} onChange={event=>{setSuite(event.target.value);setSelected([]);}}><option value="">全部套系</option>{[...new Set(rows.map(row=>row.suite_name))].map(name=><option key={name}>{name}</option>)}</select></label><label><input type="checkbox" checked={selectable.length>0&&selectable.every(item=>selected.includes(item.id))} onChange={event=>setSelected(event.target.checked?selectable.map(item=>item.id):[])}/>全选待审核</label><button className="button button-primary" disabled={busy||!selected.length} onClick={()=>confirm(selected)}><Check size={16}/>确认所选 {selected.length||''}</button></div>
 {!visible.length&&<p className="visual-queue-empty">当前没有待处理的视觉规则。已发布素材可在项目库查看。</p>}<div className="visual-revision-list">{visible.map(item=><article key={item.id}><input aria-label={`选择 ${item.display_name}`} type="checkbox" disabled={item.status!=='PENDING'||item.reuse_state==='NOT_REUSABLE'} checked={selected.includes(item.id)} onChange={event=>setSelected(value=>event.target.checked?[...value,item.id]:value.filter(id=>id!==item.id))}/><button className="visual-row-open" onClick={()=>setCurrent(item.id)}><img src={`/api/assets/${item.asset_id}/preview`} alt={item.display_name}/><span><b>{item.display_name||item.filename}</b><small>{item.suite_name}</small><small>{statuses[item.status]??item.status}{!item.active_visual_revision_id?' · 旧版规则':''}</small>{['QUEUED','ANALYZING','APPROVED','PROCESSING_TEXT','PROCESSING_IMAGE'].includes(item.status)&&<progress aria-label={statuses[item.status]}/>}</span></button>{['FAILED','WAITING_ELIGIBILITY'].includes(item.status)&&<button title="重试" disabled={busy} className="icon-button" onClick={()=>upgrade([item.asset_id])}><RefreshCw size={16}/></button>}</article>)}</div>
 <dialog ref={dialog} className="visual-editor" onClose={()=>setCurrent(null)} aria-label="视觉规则新旧对照">{row&&<><header><h3>{row.display_name}</h3><button className="icon-button" title="关闭" onClick={()=>setCurrent(null)}><X size={18}/></button></header><div className="visual-editor-body"><aside><img src={`/api/assets/${row.asset_id}/preview`} alt={row.display_name}/>{row.active_profile&&JSON.stringify(row.active_profile)!==JSON.stringify(edit?.profile)?<details className="visual-previous"><summary>对照上次发布内容</summary><VisualProfileView profile={row.active_profile}/></details>:<p className="visual-preview-caption">{row.active_profile?'右侧为视觉字段，已省略重复摘要。':'对照原图逐项确认视觉字段。'}</p>}</aside><div>{row.error_message&&<p role="alert">{row.error_message}</p>}{edit?.profile?Object.entries(GROUPS).map(([key,definition])=>{const group=edit.profile[key as keyof VisualProfile];const options=key==='title'?TITLE_TYPES:key==='selling'?SELLING_TYPES:key==='subject'?Object.fromEntries(SUBJECT_TYPES.map(value=>[value,[value]])):null;const update=(field:string,value:string|string[]|number)=>change({...edit.profile,[key]:{...group,[field]:value}},edit.notes);return <fieldset key={key} disabled={row.status!=='PENDING'}><legend>{definition.label}{group.confidence<.8?' · 低置信度':''}</legend><label>观察状态<select value={group.status} onChange={event=>change({...edit.profile,[key]:{...group,status:event.target.value as typeof group.status,types:['ABSENT','UNKNOWN'].includes(event.target.value)?[]:group.types}},edit.notes)}>{Object.entries({OBSERVED:'已观察',ABSENT:'未出现',UNKNOWN:'无法判断',OTHER:'其他'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{options?<div className="visual-type-options">{Object.entries(options).map(([id,label])=><label key={id}><input type="checkbox" disabled={['UNKNOWN','ABSENT'].includes(group.status)} checked={group.types.includes(id)} onChange={event=>update('types',event.target.checked?[...group.types,id]:group.types.filter(type=>type!==id))}/>{label[0]}</label>)}</div>:<label>分类词<input value={group.types.join('、')} onChange={event=>update('types',event.target.value.split(/[、，,]/).filter(Boolean))}/></label>}{definition.fields.map(field=><label key={field}>{FIELD_LABELS[field]}<input value={String(group[field])} onChange={event=>update(field,event.target.value)}/></label>)}<label>观察依据<textarea value={group.evidence} onChange={event=>update('evidence',event.target.value)}/></label><small>AI 置信度：{Math.round(group.confidence*100)}%</small></fieldset>;}):<p>{statuses[row.status]}</p>}</div></div><footer>{row.status==='READY'&&<button className="button button-secondary" disabled={busy} onClick={()=>upgrade([row.asset_id],true)}><RefreshCw size={16}/>重新识别</button>}{message&&<p role="status">{message}</p>}<button disabled={busy||row.status!=='PENDING'||!edit?.profile} className="button button-primary" onClick={()=>confirm([row.id])}><Check size={16}/>确认新视觉字段</button></footer></>}</dialog>
 </section>;
}
