export type VisualGroup = {status:'OBSERVED'|'ABSENT'|'UNKNOWN'|'OTHER';confidence:number;evidence:string;types:string[];[field:string]:string|number|string[]};
export type VisualProfile = Record<'style'|'subject'|'colors'|'composition'|'title'|'selling',VisualGroup>;
export type Constraint = {field:'title'|'selling'|'subject'|'selling.count';operator:'include'|'exclude';value:string;evidence:string};
export type Preferences = {title:string[];selling:string[];subject:string[]};
export const RULE_VERSION:string;
export const TITLE_TYPES:Record<string,string[]>;
export const SELLING_TYPES:Record<string,string[]>;
export const SELLING_RULE_VERSION:string;
export const SUBJECT_TYPES:string[];
export const GROUPS:Record<keyof VisualProfile,{label:string;fields:string[]}>;
export const FIELD_LABELS:Record<string,string>;
export const OBSERVATIONS:string[];
export const PROFILE_PROMPT:string;
export const BRIEF_PROMPT:string;
export function emptyProfile():VisualProfile;
export function validateProfile(value:unknown):VisualProfile;
export function profileSections(value:VisualProfile):string[];
export function validateBriefRules<T>(value:T):T;
export function matchesConstraints(value:VisualProfile|null|undefined, constraints:Constraint[]):boolean;
export function preferenceMatch(value:VisualProfile|null|undefined, preferences:Preferences):{matched:string[];missed:string[];ratio:number};
export function normalizeBriefConstraints<T extends {unsupportedConstraints:string[];assumptions:string[]}>(analysis:T):T;
export function validStyleKeywords(value:unknown):boolean;
